

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author hc745
 */
public class bill extends javax.swing.JFrame {

    

    

    /**
     * Creates new form bill
     */
    public bill() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        TokenNm = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        BGroup = new javax.swing.JLabel();
        RegNm = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        HName = new javax.swing.JLabel();
        Address = new javax.swing.JLabel();
        BUnit = new javax.swing.JLabel();
        Distance = new javax.swing.JLabel();
        Amount = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();

        jButton2.setText("Generate Bill");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(340, 130));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel1.setText("Estimate");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 6, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 60, 688, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Hospital Reg Nm  :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 130, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Hospital Name     :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 130, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Hospital Address :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 130, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 688, 10));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\NetBeansProjects\\BloodDoation\\src\\main\\java\\Images\\search1.png")); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, -1, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\NetBeansProjects\\BloodDoation\\src\\main\\java\\Images\\Exit application.png")); // NOI18N
        jButton3.setText("Close");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Blood Units         :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 120, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Delivery Distance(KM)  :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 160, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Total Amount :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 110, -1));

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\NetBeansProjects\\BloodDoation\\src\\main\\java\\Images\\save.png")); // NOI18N
        jButton5.setText("Save");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Date :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 50, -1));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Per KM Charge :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 110, 20));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("15");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 50, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Per Unit Charge :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 120, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("1000");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 50, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Token No.");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 80, 30));

        TokenNm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TokenNm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TokenNmActionPerformed(evt);
            }
        });
        getContentPane().add(TokenNm, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 80, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Blood Group       :");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 120, 30));

        BGroup.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BGroup.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(BGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 50, 20));

        RegNm.setBackground(new java.awt.Color(255, 204, 204));
        RegNm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RegNm.setForeground(new java.awt.Color(255, 102, 102));
        getContentPane().add(RegNm, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 100, 20));

        Date.setBackground(new java.awt.Color(255, 204, 204));
        Date.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Date.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 90, 20));

        HName.setBackground(new java.awt.Color(255, 204, 204));
        HName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        HName.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(HName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 270, 30));

        Address.setBackground(new java.awt.Color(255, 204, 204));
        Address.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Address.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 290, 40));

        BUnit.setBackground(new java.awt.Color(255, 204, 204));
        BUnit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BUnit.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(BUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 80, 20));

        Distance.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Distance.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(Distance, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 80, 30));

        Amount.setBackground(new java.awt.Color(255, 204, 204));
        Amount.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Amount.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(Amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 100, 30));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 433, 680, 10));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\NetBeansProjects\\BloodDoation\\src\\main\\java\\Images\\all page background image.png")); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String token=TokenNm.getText();
        try{
            Connection con=ConnectionProvider.getCon();
            Statement st=con.createStatement();
            var rs=st.executeQuery("select *FROM orderdetails where SNo='"+token+"'");
            if(rs.next()){
            RegNm.setText(rs.getString(2));
            HName.setText(rs.getString(3));
            Address.setText(rs.getString(4));
            BGroup.setText(rs.getString(5));
            BUnit.setText(rs.getString(6));
            Date.setText(rs.getString(7));
            rs=st.executeQuery("select *FROM delivery where Token='"+token+"'");
            if(rs.next()){
            Distance.setText(rs.getString(4));
            Amount.setText(rs.getString(6));
            }
            }
            else
                JOptionPane.showMessageDialog(null,"Hospital Id does not exist");
           }
        catch(Exception e){}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
            
           
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String Sn=TokenNm.getText();
        String RegId=RegNm.getText();
        String Hname=HName.getText();
        String add =Address.getText();
        String bloodGroup =BGroup.getText();
        String unit =BUnit.getText();
       String Dis = Distance.getText();
       String amt = Amount.getText();
       String date = Date.getText();
    
    
    
    try {
        Connection con = ConnectionProvider.getCon();
        Statement st = con.createStatement();
         PreparedStatement ptr=null;
        // Check if the requested units are available in stock {
               String query ="Insert into Bill(Token,RegNo,HospitalName,Address,BloodGroup,Unit,Distance,Amount,Date)values(?,?,?,?,?,?,?,?,?)";
                ptr =con.prepareStatement(query);
                ptr.setString(1,Sn);
                ptr.setString(2,RegId);
                ptr.setString(3,Hname);
                 ptr.setString(4,add);
                 ptr.setString(5,bloodGroup);
                 ptr.setString(6,unit);  
                 ptr.setString(7,Dis);
                 ptr.setString(8,amt);
                 ptr.setString(9,date);
                 ptr.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Bill Successfully Save");
                setVisible(false);
                new bill().setVisible(true);
         
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void TokenNmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TokenNmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TokenNmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JLabel Amount;
    private javax.swing.JLabel BGroup;
    private javax.swing.JLabel BUnit;
    private javax.swing.JLabel Date;
    private javax.swing.JLabel Distance;
    private javax.swing.JLabel HName;
    private javax.swing.JLabel RegNm;
    private javax.swing.JTextField TokenNm;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
